### PR TITLE
Shared titles and axes

### LINKED ISSUE #150: Combine axes/scales
I often have a case where I have two plots with the same y-axis scales that I would like to show side by side, with the axis only showing on the outer plot. Currently, I need to manually set the axis scales to be the same across plots and set the axis to be element_blank() for one of the plots. 

Would it be possible to add functions to do these steps within the patchwork composition, similar to the legend collapsing?

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #150.

Briefly, it adds options to `plot_layout()` that allows the user to:

1. Collect titles, i.e. deduplicate them and merge them
2. Deduplicate axes

What can and cannot be merged is mostly determined by a homebrew 2D run-length encoding of a simplified layout.

An example using identical plots to showcase the sharing.
Notice the following:

* The 2-cell plot breaks continuity so nothing is shared 'across' that plot.
* The rightmost 4 plots share titles and axes, almost acting like facets.

``` r
library(ggplot2)
devtools::load_all("~/packages/patchwork/")
#> ℹ Loading patchwork

# loading dev patchwork overrides theme
theme_set(theme_grey())

p1 <- ggplot(mtcars) +
  aes(x = cyl, y = disp) +
  geom_point() +
  guides(x.sec = "axis", y.sec = "axis")

layout <- plot_layout(
  design = c("1234\n5267"),
  collect_titles = "both",
  dedup_axes = "both"
)

p1 + p1 + p1 + p1 + p1 + p1 + p1 + layout
```

Another example showing not-merge behaviour for the last plot.
Notice the following:

* Cells [1, 3] and [1,4] two plots on the top right continue sharing y-axes/axis-title.
* Cells [1, 3] and [2, 3] continue sharing x-axis/axis-title.

``` r
p2 <- p1 + theme(axis.text = element_text(colour = "red")) + 
  labs(x = "foo", y = "bar")

p1 + p1 + p1 + p1 + p1 + p1 + p2 + layout
```

<sup>Created on 2023-10-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Why is this PR still WIP?

* Haven't thought deeply how this functionality will be exposed to user.
* Other than not merging over nested patches, this approach is totally blind to nested patches. Should it be blind to that?
* Need to add unit tests, but I'm still looking for a few challenging cases.
* ~I have no idea (yet) how this interacts with facetting.~ Facetted plots don't share titles or axes.
* Resizing after deleting grobs does not take into account sizes of remaining grobs, as can be seen in the example below where we have long y-axis text. However, this information isn't retained somewhere, so it probably can only be done by measuring the remaining grobs themselves?

``` r
p1 <- p1 + scale_y_continuous(labels = \(x) paste0(x, " but with longer stuff")) +
  guides(x.sec = "none", y.sec = "none")

p1 + p1 + p1 + p2 + plot_layout(2, 2, dedup_axes = "y")
```

### CODE REVIEW

**Comment by thomasp85** [comment]
- Haven't thought deeply how this functionality will be exposed to user.
  - I don't like the `dedup_axes` name and think the functionality should work in the same way as the guide collecting functionality. This suggests adding a `axes` and `axis_titles` argument to `plot_layout()` that can take `"keep"` and `"collect"` as values
- Other than not merging over nested patches, this approach is totally blind to nested patches. Should it be blind to that?
  - Yes, the axis functionality should only work in one nesting level
- I have no idea (yet) how this interacts with facetting. Facetted plots don't share titles or axes.
  - axis title collecting can still work as normally but any plot with multiple axes in the collection direction should be ignored
- Resizing after deleting grobs does not take into account sizes of remaining grobs, as can be seen in the example below where we have long y-axis text. However, this information isn't retained somewhere, so it probably can only be done by measuring the remaining grobs themselves?
  - Yeah, this should be fixed somehow

**Comment by teunbrand** [comment]
Thanks for your thoughts Thomas!

> This suggests adding a axes and axis_titles argument to plot_layout() that can take "keep" and "collect" as values

Is there a need to discriminate the x- or y-direction and if so, how would you like this to be exposed? We could add `x_axes = NULL` and `y_axes = NULL` arguments, where `x_axes = x_axes %||% axes` or something. Or should the options be `"keep"`, `"collect"`, `"collect_x"` and `"collect_y"`?

**Comment by thomasp85** [comment]
If we should discriminate I think the last suggestion is the best since we already have committed to string values

**Comment by teunbrand** [comment]
Latest updates:

* Refurbished arguments so that now `axis = 'collect{_x/_y}'` can be used and `axis_titles` in similar fashion.
* Fixed the spacing issue after large axis is removed.

I think this PR is now in a good place for review.

``` r
library(ggplot2)
devtools::load_all("~/packages/patchwork/")
#> ℹ Loading patchwork

theme_set(theme_grey())

p1 <- ggplot(mtcars) +
  aes(x = cyl, y = disp) +
  geom_point()

p2 <- p1 + 
  theme(axis.text = element_text(colour = "red")) + 
  labs(x = "foo", y = "bar") 

p1 <- p1 + scale_y_continuous(labels = \(x) paste0("a long label indicating ", x))

p1 + p1 + p1 + p2 + plot_layout(2, 2, axes = "collect", axis_titles = "collect")
```



<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
Thank you!

**Comment by bwiernik** [comment]
Amazing!

**Comment by pabloabur** [comment]
Hi,

It seems like this doesn't do anything when we use `|` and `/` instead of `plot_layout` definition. Is this intended?

```
p1 <- ggplot(mtcars) +
  aes(x = cyl, y = disp) +
  geom_point()

p2 <- p1 + 
  theme(axis.text = element_text(colour = "red")) + 
  labs(x = "foo", y = "bar") 

p1 <- p1 + scale_y_continuous(labels = \(x) paste0("a long label indicating ", x))

(p1 | p1) / (p1 | p2) + plot_layout(axes = "collect", axis_titles = "collect")

```
test

**Comment by teunbrand** [comment]
> Is this intended?

Yes and no. The merging mechanism don't work over multiple nesting levels, which is what you've induced with your layout code. We had accepted this limitation, so while we agree that it doesn't work out ideally in your case, it generally does what we had intended. The solution to the problem would be to use an unnested layout design.

**Comment by pabloabur** [comment]
Fair enough. Is there a way to raise a warning in this situation? Or alternatively mention it on the documentation? I could make a pull request (although the former seems to be complicated)

**Pull request merged**
