### PR TITLE
Add a search bar to website

### PR DESCRIPTION
**Pull request by olivroy**
Update pkgdown config.

Here is the new look
image

### CODE REVIEW

**Comment by olivroy** [comment]
@thomasp85, if you prefer, I can break this down in smaller PRs? and just add this to `_pkgdown.yml` in this one.

```yaml
template:
  bootstrap: 5
```

**Comment by thomasp85** [comment]
Nah, this is fine - maybe just leave the DESCRIPTION file alone as that isn't relevant to this

**Comment by olivroy** [comment]
Done, thanks! I just left the `Config/Needs/website: gifski` as it is recommended to declare dependencies in DESCRIPTION rather than in GitHub actions.

**Comment by thomasp85** [comment]
Yes for sure - thanks a bunch!

**Pull request merged**
