### PR TITLE
add option `align_axis_title`

### LINKED ISSUE #285: Gap between axis label and text if adjacent plot has vertical axis text
Please check the following code. Is there a way to remove this gap ignoring the other plots?

``` r
library(tidyverse)

df1 = data.frame(Group = factor(1:10), Value = runif(10))
df2 = data.frame(Group = factor(1:10), Long_label_A = runif(10), Long_label_B = runif(10), Long_label_C = runif(10)) %>% 
  gather(Label, X, -Group)

p1 = ggplot(df1, aes(Value, Group)) + 
  geom_col(orientation = "y", position = "identity")

p2 = ggplot(df2, aes(Label, Group, fill = X)) + 
  geom_tile() +
  ylab("") +
  theme_void() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

library(patchwork)

p1 + p2 + plot_layout(nrow = 1, widths = c(0.9, 0.1))
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by Yunuuuu**
fix https://github.com/thomasp85/patchwork/issues/285, https://github.com/thomasp85/patchwork/issues/348 and https://github.com/thomasp85/patchwork/issues/110#issuecomment-615000426

This PR provide the option to disable the alignment of the axis title.

``` r
library(tidyverse)
library(patchwork)

df1 <- data.frame(Group = factor(1:10), Value = runif(10))
df2 <- data.frame(Group = factor(1:10), Long_label_A = runif(10), Long_label_B = runif(10), Long_label_C = runif(10)) %>%
  gather(Label, X, -Group)

p1 <- ggplot(df1, aes(Value, Group)) +
  geom_col(orientation = "y", position = "identity")

p2 <- ggplot(df2, aes(Label, Group, fill = X)) +
  geom_tile() +
  ylab("") +
  theme_void() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

p1 + p2 + plot_layout(
      nrow = 1, widths = c(0.9, 0.1),
      align_axis_title = FALSE
    )
```
image

<sup>Created on 2024-08-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                                                     
~

### CODE REVIEW

**Comment by Yunuuuu** [comment]
This is commonly requested in stackoverflow:
1. https://stackoverflow.com/questions/76189627/control-y-axis-title-positions-when-combining-several-plots-with-patchwork-packa
2. https://stackoverflow.com/questions/62304750/ignore-x-label-alignment-with-multiple-plots-in-patchwork-is-this-possible

**Comment by Yunuuuu** [comment]
Anothe example in https://github.com/thomasp85/patchwork/issues/348
``` r
library(ggplot2)
library(tibble)
library(patchwork)

df <- mtcars |>
  rownames_to_column("car") |>
  as_tibble()

gg1 <- df |>
  ggplot(aes(y = wt, x = car)) +
  geom_col() +
  theme_bw() +
  xlab(NULL) +
  ylab("Plot 1") +
  theme(axis.text.x = element_blank())


gg2 <- df |>
  ggplot(aes(y = "number_of_cylinders", x = car, fill = as.character(cyl))) +
  geom_tile(width = 0.9) +
  ylab("Plot 2") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
gg1 / gg2 + plot_layout(align_axis_title = FALSE)
```

<sup>Created on 2024-08-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                                                     
~                                                                                     
~                                                                                     
~                                                                                     
~             
image

**Comment by Yunuuuu** [comment]
Examples in comment https://github.com/thomasp85/patchwork/issues/110#issuecomment-615000426
``` r
library(patchwork)
library(ggplot2)

p1 <- ggplot(diamonds, aes(clarity, price)) +
  geom_boxplot() +
  coord_flip()

lev <- levels(diamonds$cut)
long_label <- paste("Very Very Very Very", lev)
names(long_label) <- lev
p2 <- ggplot(diamonds, aes(cut, price)) +
  geom_boxplot() +
  scale_x_discrete(labels = long_label) +
  coord_flip()
p1 + p2 + plot_layout(ncol = 1, align_axis_title = FALSE)
```

<sup>Created on 2024-08-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                                                    
 
image

**Comment by Yunuuuu** [comment]
Another example for facet panels:

``` r
library(patchwork)
library(ggplot2)

p <- ggplot(mpg, aes(displ, cty)) +
    geom_point()
p1 <- p + facet_grid(rows = vars(drv))
p2 <- p + facet_grid(vars(drv), vars(cyl))
p3 <- p + facet_wrap(vars(class))
p1 + (p2 + scale_y_continuous(labels = ~ paste0("very very long ", .x))) +
    plot_layout(align_axis_title = FALSE, ncol = 1L)
```
image

```r
p3 + (p2 + scale_y_continuous(labels = ~ paste0("very very long ", .x))) +
    plot_layout(align_axis_title = FALSE, ncol = 1L)
```
image

<sup>Created on 2024-08-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                                                     
~                                                                                     
~                                                                                     
~

**Comment by Yunuuuu** [comment]
Dear @thomasp85,

I apologize for any inconvenience caused and kindly request your assistance in integrating this function into my package. The functionality of my package heavily depends on this particular function.

I have developed a [package](https://github.com/Yunuuuu/ggalign) that utilizes ggplot2 to generate complex heatmaps. The package functions smoothly, but it heavily relies on this specific function. Without integrating this function, there would be some areas with no data. If it is not possible to merge it in `patchwork`, I will continue with other tasks in my package.

Some figures created with this package. 
ggalign (2)

**Comment by Yunuuuu** [comment]
After learning `patchwork` project, I found a better method to implement this, including a series of functions:
 - `free_align()`
 - `free_border()`
 - `free_lab()`
 - `free_size`

These function need lots of modifications of patchwork, I'll make another commits for this. Now I'll close this thread.

**Comment by thomasp85** [comment]
Hi @Yunuuuu - thanks for your wish to improve upon patchwork. Before you spend too much time on new features it would be better to open an issue where your ideas can be discussed. In that way we can ensure that your time is best spend on work that will end up in the package

**Comment by Yunuuuu** [comment]
Thanks @thomasp85 for your advice.

I have made an issue to follow this

**Comment by aconrrero** [comment]
The align_axis_title  argument does not exist anymore in patchwork ‘1.3.2’ ? Is there a reason why you removed it? 

```
Error in plot_layout(heights = c(1, 3), guides = "collect", align_axis_title = FALSE) : 
  unused argument (align_axis_title = FALSE)
```

**Pull request closed without merging**
