### PR TITLE
Fix a small example code typo in plot_annotation.Rd

### PR DESCRIPTION
**Pull request by sixvable**
I found a small code typo in plot_annotation.Rd 's example.

# Add multilevel tagging to nested layouts
`p1 / (p2 | p3 + plot_layout(tag_level = 'new')) +
  plot_annotation(tag_levels = c('A', '1'))`
It makes p2 and p3 two separate objects but not a patchwork object so the 
`+ plot_layout(tag_level = 'new')` 
only be set up to p3, which makes the final tag is **"A/B/C1"**.

I change the code to  
`p1 / ((p2 | p3) + plot_layout(tag_level = 'new')) +
  plot_annotation(tag_levels = c('A', '1'))` 
so the tag becomes to **"A/B1/B2"**, which I assume is the original purpose。

### CODE REVIEW

**Comment by thomasp85** [comment]
Hi, thanks! Can I get you to fix the relevant oxygen comment as well, since the .Rd files are generated from that

**Comment by sixvable** [comment]
> Hi, thanks! Can I get you to fix the relevant oxygen comment as well, since the .Rd files are generated from that

Job finished!

**Comment by sixvable** [comment]
> You might need to remove one parenthesis after `plot_layout`

If I remove the  parenthesis then it wont be a new tag_level.

`p1 / ((p2 | p3) + plot_layout(tag_level = 'new')) + plot_annotation(tag_levels = c('A', '1'))` is same with `p1 / (p2 | p3)+ plot_annotation(tag_levels = c('A', '1'))`

**Comment by sixvable** [comment]
> You might need to remove one parenthesis after `plot_layout`

I am a little bit confused ,could u show which one should I removed.

**Comment by llrs** [comment]
Sorry, my mistake, I thought it would work with

```r
p1 / ((p2 | p3) + plot_layout(tag_level = 'new') +
    plot_annotation(tag_levels = c('A', '1')))
```
But then it doesn't show the B1 and B2 labels

**Comment by thomasp85** [comment]
Thanks!

**Pull request merged**
